# Generated by Django 5.0.7 on 2024-07-29 14:41

import datetime
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('file', models.FileField(upload_to='files')),
                ('name', models.CharField(max_length=45)),
                ('path', models.CharField(max_length=100, null=True)),
                ('request_code', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(db_index=True, default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(seconds=600))), editable=False)),
            ],
        ),
    ]
