# Generated by Django 5.0.7 on 2024-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='request_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
